# Generated by Django 3.2.25 on 2024-07-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=2000)),
                ('equipment', models.CharField(max_length=1000)),
                ('method', models.CharField(max_length=5000)),
            ],
        ),
    ]
